package com.coralogix.jdbc

import java.sql.ResultSet

trait UnsupportedStatementMethods extends UnsupportedMethods { self: StatementImpl =>

  override def executeUpdate(sql: String): Int = unsupported

  override def addBatch(sql: String): Unit = unsupported

  override def clearBatch(): Unit = unsupported

  override def executeBatch(): Array[Int] = unsupported

  override def getGeneratedKeys: ResultSet = unsupported

  override def executeUpdate(sql: String, autoGeneratedKeys: Int): Int = unsupported

  override def executeUpdate(sql: String, columnIndexes: Array[Int]): Int = unsupported

  override def executeUpdate(sql: String, columnNames: Array[String]): Int = unsupported

  override def execute(sql: String, columnIndexes: Array[Int]): Boolean = unsupported

  override def execute(sql: String, columnNames: Array[String]): Boolean = unsupported

  override def setPoolable(poolable: Boolean): Unit = unsupported

  override def setFetchDirection(direction: Int): Unit = unsupported

  override def getMaxFieldSize: Int = unsupported

  override def setMaxFieldSize(max: Int): Unit = unsupported

  override def setEscapeProcessing(enable: Boolean): Unit = unsupported

  override def unwrap[T](iface: Class[T]): T = unsupported
}
